const cfg=window.ATMO_CONFIG||{};
const configured=cfg.SUPABASE_URL&&!cfg.SUPABASE_URL.includes('YOUR_PROJECT')&&cfg.SUPABASE_ANON_KEY&&!cfg.SUPABASE_ANON_KEY.includes('YOUR_SUPABASE');
const sb=configured?supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null;
const money=n=>new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND',maximumFractionDigits:0}).format(Number(n||0));
const round1000=n=>Math.ceil((Number(n)||0)/1000)*1000;
const uid=()=>crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random());
const defaultSettings={machinePerHour:2000,electricityPrice:3000,powerKw:.18,laborPerHour:30000,failureRate:.08,profitRate:.80,socialFee:.03,shopeeFee:.18,tiktokFee:.20};
let authMode='login', currentUser=null, data={settings:{...defaultSettings},materials:[],products:[]};

const $=id=>document.getElementById(id), val=id=>$(id).value, num=id=>Number(val(id))||0, setVal=(id,v)=>{$(id).value=v??''}, fmt=n=>new Intl.NumberFormat('vi-VN').format(Number(n||0)), esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
function setSync(text,state=''){const el=$('syncStatus');if(!el)return;el.textContent=text;el.className='sync-status'+(state?' '+state:'')}
function unitCost(m){return m&&m.packQty?m.purchasePrice/m.packQty:0} function matById(id){return data.materials.find(m=>m.id===id)}

function calc(p){const s=data.settings,plateQty=Math.max(1,Number(p.plateQty)||1),hours=Number(p.plateHours)||0;
 const plastics=(p.plastics||[]).reduce((sum,x)=>sum+(Number(x.qty)||0)/plateQty*unitCost(matById(x.materialId)),0);
 const acc=(p.accessories||[]).reduce((sum,x)=>sum+(Number(x.qty)||0)*unitCost(matById(x.materialId)),0);
 const pack=(p.packaging||[]).reduce((sum,x)=>sum+(Number(x.qty)||0)*unitCost(matById(x.materialId)),0);
 const electricityPlate=hours*s.powerKw*s.electricityPrice,electricity=electricityPlate/plateQty,machinePlate=hours*s.machinePerHour,machine=machinePlate/plateQty;
 const post=((Number(p.supportMinutes)||0)+(Number(p.surfaceMinutes)||0))/60*s.laborPerHour;
 const pre=plastics+acc+pack+electricity+machine+post+(Number(p.otherCost)||0),failure=pre*s.failureRate,cost=pre+failure;
 return {plastics,acc,pack,electricityPlate,electricity,machinePlate,machine,post,pre,failure,cost,direct:round1000(cost*(1+s.profitRate)),social:round1000(cost*(1+s.profitRate)/(1-s.socialFee)),shopee:round1000(cost*(1+s.profitRate)/(1-s.shopeeFee)),tiktok:round1000(cost*(1+s.profitRate)/(1-s.tiktokFee))};}

async function init(){if(!configured){showAuthMessage('Chưa cấu hình Supabase. Hãy điền SUPABASE_URL và SUPABASE_ANON_KEY trong config.js.');return}
 const {data:{session}}=await sb.auth.getSession(); await handleSession(session);
 sb.auth.onAuthStateChange(async(_event,session)=>{await handleSession(session)});
}
async function handleSession(session){currentUser=session?.user||null;$('authScreen').hidden=!!currentUser;$('appShell').hidden=!currentUser;if(currentUser){$('userEmail').textContent=currentUser.email||'';await loadCloud();renderAll()}else{$('userEmail').textContent=''}}
function showAuthMessage(msg,ok=false){const el=$('authMessage');el.textContent=msg||'';el.style.color=ok?'#15803d':'#dc2626'}
function setAuthMode(mode){authMode=mode;$('authLoginTab').classList.toggle('active',mode==='login');$('authSignupTab').classList.toggle('active',mode==='signup');$('authSubmit').textContent=mode==='login'?'Đăng nhập':'Tạo tài khoản';$('authPassword').autocomplete=mode==='login'?'current-password':'new-password';showAuthMessage('')}
$('authLoginTab').onclick=()=>setAuthMode('login');$('authSignupTab').onclick=()=>setAuthMode('signup');
$('authForm').onsubmit=async e=>{e.preventDefault();showAuthMessage('');const email=val('authEmail').trim(),password=val('authPassword');$('authSubmit').disabled=true;try{if(authMode==='login'){const {error}=await sb.auth.signInWithPassword({email,password});if(error)throw error}else{const {data:r,error}=await sb.auth.signUp({email,password,options:{emailRedirectTo:'https://thanhan671.github.io/atmo-costing/'}});if(error)throw error;if(!r.session)showAuthMessage('Đã tạo tài khoản. Hãy kiểm tra email xác nhận rồi đăng nhập.',true)}}catch(err){showAuthMessage(err.message||'Không thể đăng nhập.')}finally{$('authSubmit').disabled=false}};
$('btnLogout').onclick=()=>sb.auth.signOut();

async function loadCloud(){setSync('Đang tải…','saving');const uid=currentUser.id;
 const [m,p,s]=await Promise.all([sb.from('materials').select('*').eq('user_id',uid).order('created_at'),sb.from('products').select('*').eq('user_id',uid).order('created_at'),sb.from('app_settings').select('settings').eq('user_id',uid).maybeSingle()]);
 const err=m.error||p.error||s.error;if(err){setSync('Lỗi đồng bộ','error');throw err}
 data.materials=(m.data||[]).map(r=>({id:r.id,code:r.code,name:r.name,group:r.group_name,unit:r.unit,packQty:Number(r.pack_qty),purchasePrice:Number(r.purchase_price)}));
 data.products=(p.data||[]).map(r=>({id:r.id,code:r.code,name:r.name,plateQty:Number(r.plate_qty),plateHours:Number(r.plate_hours),plastics:r.plastics||[],accessories:r.accessories||[],packaging:r.packaging||[],supportMinutes:Number(r.support_minutes||0),surfaceMinutes:Number(r.surface_minutes||0),otherCost:Number(r.other_cost||0)}));
 data.settings={...defaultSettings,...(s.data?.settings||{})};setSync('Đã đồng bộ');}
async function saveSettingsCloud(){setSync('Đang lưu…','saving');const {error}=await sb.from('app_settings').upsert({user_id:currentUser.id,settings:data.settings,updated_at:new Date().toISOString()},{onConflict:'user_id'});if(error){setSync('Lỗi đồng bộ','error');throw error}setSync('Đã đồng bộ')}
async function upsertMaterial(m){setSync('Đang lưu…','saving');const row={id:m.id,user_id:currentUser.id,code:m.code,name:m.name,group_name:m.group,unit:m.unit,pack_qty:m.packQty,purchase_price:m.purchasePrice,updated_at:new Date().toISOString()};const {error}=await sb.from('materials').upsert(row);if(error){setSync('Lỗi đồng bộ','error');throw error}setSync('Đã đồng bộ')}
async function deleteMaterialCloud(id){setSync('Đang lưu…','saving');const {error}=await sb.from('materials').delete().eq('id',id);if(error){setSync('Lỗi đồng bộ','error');throw error}setSync('Đã đồng bộ')}
async function upsertProduct(p){setSync('Đang lưu…','saving');const row={id:p.id,user_id:currentUser.id,code:p.code,name:p.name,plate_qty:p.plateQty,plate_hours:p.plateHours,plastics:p.plastics,accessories:p.accessories,packaging:p.packaging,support_minutes:p.supportMinutes,surface_minutes:p.surfaceMinutes,other_cost:p.otherCost,updated_at:new Date().toISOString()};const {error}=await sb.from('products').upsert(row);if(error){setSync('Lỗi đồng bộ','error');throw error}setSync('Đã đồng bộ')}
async function deleteProductCloud(id){setSync('Đang lưu…','saving');const {error}=await sb.from('products').delete().eq('id',id);if(error){setSync('Lỗi đồng bộ','error');throw error}setSync('Đã đồng bộ')}

function switchTab(name){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',x.id===`tab-${name}`))}document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));
function renderMaterials(){const tb=document.querySelector('#materialTable tbody');tb.innerHTML='';if(!data.materials.length){tb.innerHTML='<tr><td colspan="8" class="empty">Chưa có nguyên vật liệu.</td></tr>';return}data.materials.forEach(m=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${esc(m.code)}</td><td>${esc(m.name)}</td><td><span class="badge ${m.group}">${m.group}</span></td><td>${esc(m.unit||'')}</td><td class="num">${fmt(m.packQty)}</td><td class="num">${money(m.purchasePrice)}</td><td class="num">${money(unitCost(m))}</td><td class="actions"><button class="small-btn" data-edit="${m.id}">Sửa</button><button class="small-btn danger" data-del="${m.id}">Xóa</button></td>`;tb.appendChild(tr)});tb.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openMaterial(b.dataset.edit));tb.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{if(confirm('Xóa nguyên vật liệu này?')){try{await deleteMaterialCloud(b.dataset.del);data.materials=data.materials.filter(x=>x.id!==b.dataset.del);renderAll()}catch(e){alert(e.message)}}})}
function renderProducts(){const tb=document.querySelector('#productTable tbody');tb.innerHTML='';if(!data.products.length){tb.innerHTML='<tr><td colspan="16" class="empty">Chưa có sản phẩm. Bấm “Thêm sản phẩm” để bắt đầu.</td></tr>';return}data.products.forEach(p=>{const c=calc(p),tr=document.createElement('tr');tr.innerHTML=`<td>${esc(p.code)}</td><td>${esc(p.name)}</td><td class="num">${fmt(p.plateQty)}</td><td class="num">${fmt(p.plateHours)}</td><td class="num">${money(c.plastics)}</td><td class="num">${money(c.acc)}</td><td class="num">${money(c.pack)}</td><td class="num">${money(c.electricity)}</td><td class="num">${money(c.machine)}</td><td class="num">${money(c.post)}</td><td class="num"><strong>${money(c.cost)}</strong></td><td class="num">${money(c.direct)}</td><td class="num">${money(c.social)}</td><td class="num">${money(c.shopee)}</td><td class="num">${money(c.tiktok)}</td><td class="actions"><button class="small-btn" data-edit="${p.id}">Sửa</button><button class="small-btn danger" data-del="${p.id}">Xóa</button></td>`;tb.appendChild(tr)});tb.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openProduct(b.dataset.edit));tb.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{if(confirm('Xóa sản phẩm này?')){try{await deleteProductCloud(b.dataset.del);data.products=data.products.filter(x=>x.id!==b.dataset.del);renderProducts()}catch(e){alert(e.message)}}})}
function renderSettings(){const s=data.settings;setVal('sMachinePerHour',s.machinePerHour);setVal('sElectricityPrice',s.electricityPrice);setVal('sPowerKw',s.powerKw);setVal('sLaborPerHour',s.laborPerHour);setVal('sFailureRate',s.failureRate*100);setVal('sProfitRate',s.profitRate*100);setVal('sSocialFee',s.socialFee*100);setVal('sShopeeFee',s.shopeeFee*100);setVal('sTikTokFee',s.tiktokFee*100)}function renderAll(){renderMaterials();renderProducts();renderSettings()}
function openMaterial(id){const m=id?matById(id):null;setVal('materialId',m?.id||'');setVal('mCode',m?.code||'');setVal('mName',m?.name||'');setVal('mGroup',m?.group||'Nhựa');setVal('mUnit',m?.unit||'');setVal('mPackQty',m?.packQty||'');setVal('mPurchasePrice',m?.purchasePrice||'');$('materialDialogTitle').textContent=m?'Sửa nguyên vật liệu':'Thêm nguyên vật liệu';$('materialDialog').showModal()}
$('btnAddMaterial').onclick=()=>openMaterial();$('btnSaveMaterial').onclick=async e=>{e.preventDefault();const id=val('materialId')||uid(),obj={id,code:val('mCode').trim(),name:val('mName').trim(),group:val('mGroup'),unit:val('mUnit').trim(),packQty:num('mPackQty'),purchasePrice:num('mPurchasePrice')};if(!obj.code||!obj.name||obj.packQty<=0)return alert('Vui lòng nhập đủ thông tin nguyên vật liệu.');try{await upsertMaterial(obj);const i=data.materials.findIndex(x=>x.id===id);i>=0?data.materials[i]=obj:data.materials.push(obj);renderAll();$('materialDialog').close()}catch(err){alert(err.message)}};
function groupMaterials(group){return data.materials.filter(m=>m.group===group)}function buildRows(containerId,group,values=[],plastic=false){const c=$(containerId);c.innerHTML='';for(let i=0;i<3;i++){const row=$('materialRowTemplate').content.firstElementChild.cloneNode(true),sel=row.querySelector('.mat-select'),qty=row.querySelector('.mat-qty'),u=row.querySelector('.unit-label');sel.innerHTML='<option value="">-- Không dùng --</option>'+groupMaterials(group).map(m=>`<option value="${m.id}">${esc(m.name)}</option>`).join('');const v=values[i]||{};sel.value=v.materialId||'';qty.value=v.qty??'';u.textContent=plastic?'g/PEI':'/SP';sel.onchange=updatePreview;qty.oninput=updatePreview;c.appendChild(row)}}
function readRows(containerId){return [...document.querySelectorAll(`#${containerId} .material-row`)].map(r=>({materialId:r.querySelector('.mat-select').value,qty:Number(r.querySelector('.mat-qty').value)||0})).filter(x=>x.materialId&&x.qty>0)}
function currentProductFromForm(){return {id:val('productId')||uid(),code:val('pCode').trim(),name:val('pName').trim(),plateQty:num('pPlateQty'),plateHours:num('pPlateHours'),plastics:readRows('plasticRows'),accessories:readRows('accessoryRows'),packaging:readRows('packagingRows'),supportMinutes:num('pSupportMinutes'),surfaceMinutes:num('pSurfaceMinutes'),otherCost:num('pOtherCost')}}
function updatePreview(){const c=calc(currentProductFromForm());$('costPreview').innerHTML=`<div>Nhựa/SP<strong>${money(c.plastics)}</strong></div><div>Điện + máy/SP<strong>${money(c.electricity+c.machine)}</strong></div><div>Hậu xử lý/SP<strong>${money(c.post)}</strong></div><div>Giá vốn/SP<strong>${money(c.cost)}</strong></div><div>Trực tiếp<strong>${money(c.direct)}</strong></div><div>MXH<strong>${money(c.social)}</strong></div><div>Shopee<strong>${money(c.shopee)}</strong></div><div>TikTok<strong>${money(c.tiktok)}</strong></div>`}
function openProduct(id){const p=id?data.products.find(x=>x.id===id):null;setVal('productId',p?.id||'');setVal('pCode',p?.code||'');setVal('pName',p?.name||'');setVal('pPlateQty',p?.plateQty||1);setVal('pPlateHours',p?.plateHours||0);setVal('pSupportMinutes',p?.supportMinutes||0);setVal('pSurfaceMinutes',p?.surfaceMinutes||0);setVal('pOtherCost',p?.otherCost||0);buildRows('plasticRows','Nhựa',p?.plastics||[],true);buildRows('accessoryRows','Phụ kiện',p?.accessories||[]);buildRows('packagingRows','Bao bì',p?.packaging||[]);$('productDialogTitle').textContent=p?'Sửa sản phẩm':'Thêm sản phẩm';['pPlateQty','pPlateHours','pSupportMinutes','pSurfaceMinutes','pOtherCost'].forEach(id=>$(id).oninput=updatePreview);updatePreview();$('productDialog').showModal()}
$('btnAddProduct').onclick=()=>openProduct();$('btnSaveProduct').onclick=async e=>{e.preventDefault();const p=currentProductFromForm();if(!p.code||!p.name||p.plateQty<1)return alert('Vui lòng nhập Mã SP, Tên sản phẩm và số SP/PEI.');try{await upsertProduct(p);const i=data.products.findIndex(x=>x.id===p.id);i>=0?data.products[i]=p:data.products.push(p);renderProducts();$('productDialog').close()}catch(err){alert(err.message)}};
$('btnSaveSettings').onclick=async()=>{data.settings={machinePerHour:num('sMachinePerHour'),electricityPrice:num('sElectricityPrice'),powerKw:num('sPowerKw'),laborPerHour:num('sLaborPerHour'),failureRate:num('sFailureRate')/100,profitRate:num('sProfitRate')/100,socialFee:num('sSocialFee')/100,shopeeFee:num('sShopeeFee')/100,tiktokFee:num('sTikTokFee')/100};try{await saveSettingsCloud();renderProducts();alert('Đã lưu thiết lập.')}catch(e){alert(e.message)}};
$('btnExport').onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`atmo-costing-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};
$('fileImport').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{const incoming=JSON.parse(await f.text());if(!incoming.materials||!incoming.products||!incoming.settings)throw new Error('File JSON không đúng định dạng.');if(!confirm('Nhập dữ liệu sẽ ghi thêm/cập nhật dữ liệu hiện tại. Tiếp tục?'))return;for(const m of incoming.materials){m.id=m.id||uid();await upsertMaterial(m)}for(const p of incoming.products){p.id=p.id||uid();await upsertProduct(p)}data.settings={...defaultSettings,...incoming.settings};await saveSettingsCloud();await loadCloud();renderAll();alert('Đã nhập dữ liệu và đồng bộ lên cloud.')}catch(err){alert(err.message)}finally{e.target.value=''}};
init();
